### ISSUE TITLE
Bug:  이메일 회원 가입시 비밀번호 작성 규칙 불일치

### ISSUE THREAD

**Issue by Namgyu11** [100-hours-a-week/5-chunsik-4Q-be#37]
##  버그 설명

버그에 대한 명확하고 간결한 설명해주세요.

- 버그 1 영문 / 숫자 / 특문 혼합이라고 했는데 규칙을 안 지켜도 회원가입 가능
## 재현하는 방법

동작을 재현하는 단계:

## 예상한 동작

예상했던 일에 대한 명확하고 간결한 설명해주세요.

- 예상동작 1
- 예상동작 2

## 스크린샷 (옵션)

문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

## 데스크톱(다음 정보를 작성해 주세요):

- OS: [예) iOS]
- Browser [예) chrome, safari]
- Version [예) 22]

## 스마트폰(다음 정보를 입력하세요):

- Device: [예) iPhone6]
- OS: [예) iOS8.1]
- Browser [예) chrome, safari]
- Version [예) 22]

## 추가적인 내용 (옵션):

여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by HeungY** [comment]
백엔드 비밀번호 유효성 검사 추가하여 해결했습니다.
